services:
  frontend:
    x-cnc:
      type: frontend
      assets_path: dist
      build: ["npm", "run", "build"]

    build:
      dockerfile: frontend/Dockerfile
      context: frontend

  backend:
    command: ["uvicorn", "backend.asgi:application", "--port=$PORT", "--host=0.0.0.0"]

    ports:
    - "8080:8080"

    build:
      context: backend
      dockerfile: "backend/Dockerfile"

    x-cnc:
      type: backend
      url_path: /api
